[build]
  # Directorio de publicación (archivos compilados)
  publish = "dist"
  
  # Comando de build (no es necesario para esta plantilla)
  # command = ""

[build.environment]
  # Variables de entorno para el build
  NODE_VERSION = "16"

# Configuración de redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para optimización
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos CSS y JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para imágenes
[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuración de compresión
[build.processing]
  skip_processing = false

# Configuración de funciones (no necesario para este proyecto)
# [functions]
#   directory = "functions" 